FROM ruby:2.6-alpine

# Labels
LABEL maintainer="costa.marcos.pro@gmail.com"

# Install system deps
RUN apk add --update --no-cache \
  build-base \
  postgresql-dev \
  tzdata \
  less

WORKDIR /app

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "--binding", "0.0.0.0"]
